### ISSUE TITLE
Commands using avro format might have issues with special characters

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#127]
ID <523>
Reporter <@JohnJacobGuy>

Using hdfs save in sequential (complete mode) will fail quietly if using parenthesis in any of the column names. This might be an issue in other avro-based saves as well

Needs to be investigated.
Workaround is to use basic alphanumeric names as columns

at least $ ( ) . are illegal characters for avro

https://avro.apache.org/docs/1.11.1/specification/_print/#names

#341

**Comment by eemhu** [comment]
Submitted a PR with fixes for this issue

**Comment by eemhu** [comment]
Also added legacy save type support for hdfs load. This should be removed in the future.
