### ISSUE TITLE
Remove rlo_06 from | teragrep get system version

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#130]
ID <526>
Reporter <@StrongestNumber9>

> 2023-11-13T06:00:14.305+02:00	pth_10 version: 4.12.4
> 2023-11-13T06:00:14.305+02:00	rlo_06 version: null

**Comment by eemhu** [comment]
fix in commit `f8f1d6f761429ee7db26db21bfd1c8028c1ac601` (`dpl2` branch)
