### ISSUE TITLE
tonumber produces integer, there should tolong as well?

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#175]
**Describe the bug**
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
```
 
**Expected behavior**
there should be a function to covert tolong as well?
 
**How to Reproduce**
```
%dpl

| teragrep exec hdfs load search_bench_blooms | join partition [ search index=search_bench earliest=-999d ] | rename R__raw AS _raw| rename "estimate(tokens)" AS eTokens | eval estimate(tokens)=tonumber(eTokens, 10) | teragrep exec bloom create
```
 
**Screenshots**
 
**Desktop (please complete the following information):**
 
**Additional context**
com.teragrep-pth_07-5.14.0.3.g2d92443a.x86_64-1329.x86_64

**Comment by eemhu** [comment]
Pull request merged. Now returns Long instead of Integer.

**Comment by kortemik** [comment]
works!
