### ISSUE TITLE
timechart creates buckets for non-contained timerange when used with teragrep exec hdfs load

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#192]
**Describe the bug**
timechart creates buckets for non-contained timerange when used with teragrep exec hdfs load. it uses last 24 hours for buckets instead of the timerange in data.
 
**Expected behavior**
timechart should create buckets for the timerange in data.
 
**How to reproduce**
save data from the past to hdfs and then load and use timechart.
 
**Screenshots**

 
**Software version**
pth_10 4.16.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
fix implemented in internal pr

**Comment by q22u** [comment]
merged
