### ISSUE TITLE
 wildcards do not disable bloomfilter acceleration

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#193]
**Describe the bug**
when a wildcard query is used, i.e. "foo*" to search for string "foobar" no results are returned. this is because bloomfilter uses tokens (and can only use tokens) so there is only "foobar" in the filter, no foo. only way to enable wildcard queries to work is to disable the bloomfilter search acceleration. see also #191 which is related
 
**Expected behavior**
search should return data

**How to reproduce**
use wildcard based search as described
 
**Screenshots**

 
**Software version**
pth_10 4.16.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
- if wildcards are present turn off bloom filter acceleration
- if they are not present, turn it on
- In the future, perhaps the query should be run with wildcards first and tokenize only those matches, and then use those tokens for filtering. (Test performance?)
- Filter search without wildcards performs a token-based search. With wildcards, it works like the current version does without.

**Comment by eemhu** [comment]
internal pr submitted: currently checks if search statements starts or ends with `*`, should it look for it in all indices of the string?
