### ISSUE TITLE
format command does not work

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#195]
**Describe the bug**
format command does not work
 
**Expected behavior**
format command should format the query

**How to reproduce**
```
%dpl

| makeresults count=1 | eval index="1" | eval host="2" | fields index, host | format
```

should produce third column called search with following content
```
( ( host="2" AND index="1" ) )
```

additionally when given as a subsearch like
```
%dpl

[| makeresults count=1 | eval index="1" | eval host="2" | fields index, host | format]
```

search should be executed for the specified data.

this command is usually used to search for multiple values i.e. when a data is saved to hdfs then the load is used to pick the variety of search terms from the file. it is common to give arguments for the format command so the search terms are formatted as OR instead of AND.

 
**Screenshots**

 
**Software version**
4.16.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
Merged to internal dpl2 branch
