### ISSUE TITLE
Too long week/month/year relative modifier will create invalid timestamps 

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/pth_10#203]
**Describe the bug**

Too long relative modifier causes invalid timestamps

```sh
%dpl
index=x earliest=-999999999y
```

->

```sh
org.apache.spark.sql.streaming.StreamingQueryException: SQL [insert into <snip> ]; (conn=290793) Truncated incorrect datetime value: '169089589-04-28'
```

**Expected behavior**

Either limit/truncate the timestamp to SQL appropriate lengths or handle it as an error with good error description of what happened

**How to reproduce**

```sh
%dpl
index=x earliest=-999999999y
```

**Screenshots**

 
**Software version**

 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
From the error message: `^\\d{4}\\/\\d{2}-\\d{2}` seems like the maximum would be year 9999 and minimum year 1000. Perhaps need to check the year to be between these values.

**Comment by eemhu** [comment]
based on testing, 0 < epoch < int32 max value should be the valid range.

**Comment by eemhu** [comment]
internal pr merged
