### ISSUE TITLE
fillnull command

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_10#210]
**Describe the bug**
Not implemented, `| fillnull`
 
**Expected behavior**
should be implemented and functional
 
**How to reproduce**
try to run the command

**Screenshots**
 
**Software version**
pth_10 4.17.0
 
**Desktop (please complete the following information if relevant):**

**Additional context**

**Comment by eemhu** [comment]
Internal PR ready for review.

**Comment by 51-code** [comment]
Internal PR reviewed.

**Comment by eemhu** [comment]
Merged internal pr, closing
