### ISSUE TITLE
Implement accum command

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_10#216]
**Describe the bug**
`... | accum` is not implemented.
 
**Expected behavior**
Should be implemented.

**How to reproduce**
Try to run the command.

**Screenshots**
 
**Software version**
 4.17.0

**Desktop (please complete the following information if relevant):**
 
**Additional context**

**Comment by eemhu** [comment]
internal pr created

**Comment by 51-code** [comment]
Internal pr reviewed

**Comment by eemhu** [comment]
internal pr merged
