### ISSUE TITLE
replace command does not support replacing multiple values at once

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_10#218]
**Describe the bug**

`replace x with y, z with k in _raw` should be functional but only works with one `x with y` statement.
 
**Expected behavior**

should be able to replace multiple
 
**How to reproduce**

try replacing multiple values
 
**Screenshots**

 
**Software version**

4.17.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

possibly a parser limitation

**Comment by 51-code** [comment]
Fix implemented. 
Waiting for a new PTH-03 release before making a PR. There were parser fixes for this issue so the PTH-03 version has to updated in the PR as well.

**Comment by 51-code** [comment]
Note: official documentation needs to be updated after this goes to a release as the docs currently have a disclaimer about this not working.

**Comment by 51-code** [comment]
Internal PR created.
