### ISSUE TITLE
eval function sum() is not implemented

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_10#220]
**Describe the bug**
`... | eval a = sum(n0, n1, n2, ...)` is not implemented.
 
**Expected behavior**
Should return the sum of all the numbers specified. Can be directly applied as literal parameters or as a field parameter.
 
**How to reproduce**
Try to use the function.
 
**Screenshots**

 
**Software version**

4.17.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

parser issue, check ticket on pth_03

**Comment by 51-code** [comment]
Fix implemented.
Waiting for a new PTH-03 release before making a PR. There were parser fixes for this issue so the PTH-03 version has to updated in the PR as well.

**Comment by 51-code** [comment]
Internal PR created.
