### ISSUE TITLE
rex mode=sed does not allow arbitrary delimiters

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/pth_10#224]
**Describe the bug**

Can't use arbitrary delimiter 
`Invalid sed mode string was given: 's,fluffy,cute,g', but expected 's/original/replacement/g'` 
 
**Expected behavior**

Expecting `rex mode=sed` to use sed-like arguments as in the first letter after `s` is the delimiter

```sh
$ echo 'fluffy cat' | sed 's,fluffy,cute,g'
cute cat
```

**How to reproduce**

 `rex mode=sed "s,a,b,g"`

**Screenshots**

 
**Software version**

 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
internal pr merged
