### ISSUE TITLE
Fix javadoc warnings

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/pth_10#227]
**Description**

Fix javadocs warnings so you won't get flooded
```sh
100 warnings
[WARNING] Javadoc Warnings
src/main/java/com/teragrep/pth10/ast/commands/evalstatement/EvalStatement.java:1215: warning: no description for @return
[WARNING] * @return
[WARNING] ^
<snip a lot>
```
 
**Use case or motivation behind the feature request**

Better documentation for the code, IDEs can catch it for help and overall fairly counterproductive to be flooded with messages that are trivial to fix

**Related issues**

 
**Additional context**

For example:
https://github.com/teragrep/pth_10/blob/57586b4575bf084e3cc4a34bd39bca6c2166fa9a/src/main/java/com/teragrep/pth10/ast/commands/evalstatement/EvalStatement.java#L1154-L1159

**Comment by eemhu** [comment]
fixed to dpl2 branch
