### ISSUE TITLE
EarliestLatestTest fails due to relative timestamp

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_10#236]
**Describe the bug**

Some of the EarliestLatestTests fail because they test the relative time and time in the real world has progressed enough to make them fail.
 
**Expected behavior**

The tests should not break due to time progression. Perhaps the time should be somehow locked in for these tests or dataset should be generated in a way that the _time column is also progressed.
 
**How to reproduce**

Run the tests
 
**Screenshots**

 
**Software version**

4.17.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by 51-code** [comment]
Internal PR reviewed.

**Comment by eemhu** [comment]
internal pr merged
