### ISSUE TITLE
Create metadata reporting capability

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#243]
**Description**
Metadata reporting offers ability to report how much data (compressed, uncompressed, rows) is stored per index/sourcetype/app
 
**Use case or motivation behind the feature request**
Customer request for internal reporting of data volumes
 
**Related issues**
Exporting via #150 
 
**Additional context**

**Comment by eemhu** [comment]
Should this be under the `teragrep` command, for example `| teragrep exec create report [by=field] [compressed=bool] [uncompressed=bool] [rows=bool] ` where by= works like groupBy (index, sourcetype, app), and the remaining params allow choosing if certain metrics are included or not

**Comment by eemhu** [comment]
Design meeting notes:

* Add to pth-06 datasource as the tables contain a lot of data
* Add additional metadata to pre-existing metadata object
* Use a parameter / flag to indicate "metadata fetching mode" in datasource
* Use logicalStatement with special flag to indicate metadata fetching mode, see search command
* "| teragrep get archive summary"

**Comment by eemhu** [comment]
submitted pth-06 and pth-10 PRs
