### ISSUE TITLE
Relative Time uses UTC time to manipulate date(s)

### ISSUE THREAD

**Issue by q22u** [teragrep/pth_10#251]
Relative timesyntax uses utc time to cut dates.
 
Should not do this.

Test on product.

version 5.17.0

**Comment by 51-code** [comment]
Works on version 5.0.0-15-gde2b1d43 (and later).
There is no version 5.17.0 so I assume the version where this bug was found was 4.17.0.

Relative time was refactored in #28, which was merged in version 4.19.0.
