### ISSUE TITLE
invalid timestamp does not throw

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#253]
**Describe the bug**
```
latest="31/01/2012:23:59:59" 
```

month 31 <- this is not a month in my calendar!
day 01
year 2012
hour 23
minute 59
second 59
 
does not throw, but let's the query execute

**Expected behavior**
should throw an exception stating it is not a proper timestamp
 
**How to reproduce**
use such a faulty one
 
**Screenshots**

 
**Software version**
pth_10 version: 5.1.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by eemhu** [comment]
Internal PR submitted. Setting SimpleDateFormat to be non-lenient seems to fix the issue.
