### ISSUE TITLE
rex4j produces empty strings instead of nulls for empty result

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_10#257]
**Describe the bug**

rex4j empty rows should be null instead of empty string
 
**Expected behavior**

These empty rows should be of a standardized null value instead of an empty string so `isnull()` and `isnotnull()` will pick up on these values.
 
**How to reproduce**

Use rex4j with a non-matching capture group which will result in empty rows in the result column.
 
**Screenshots**

 
**Software version**

5.1.1
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

`rex` already behaves like this, `rex4j` should do the same.

**Comment by 51-code** [comment]
internal PR reviewed
