### ISSUE TITLE
teragrep syslog stream config/props do not work

### ISSUE THREAD

**Issue by eemhu** [teragrep/pth_10#263]
**Describe the bug**

The 
"dpl.pth_10.transform.teragrep.syslog.parameter.host";
"dpl.pth_10.transform.teragrep.syslog.parameter.port";
"dpl.pth_10.transform.teragrep.syslog.restrictedMode";
props do not work, because the code does not use the variables, instead it declares new ones overriding the global variables.
Probably happened in refactoring

 
**Expected behavior**

should work
 
**How to reproduce**

try changing props and then try with command parameters instead. Props do not work, but parameters in the command will.
 
**Screenshots**

 
**Software version**

5.3.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by 51-code** [comment]
Internal PR created

**Comment by 51-code** [comment]
Internal PR merged
