### ISSUE TITLE
Convert parsing tests to dataset tests

### ISSUE THREAD

**Issue by 51-code** [teragrep/pth_10#270]
**Description**

There are many disabled tests that don't test the results but rather the logical plan of the dataset. These have to be either:
- converted to streaming dataset tests with the same query
- removed to avoid duplicates, if a test has a corresponding dataset test already

**Comment by Abigael-JT** [comment]
disabled where transformation tests updated, also added some tests that were missing, created issue #277 for bugs found in where command

**Comment by Abigael-JT** [comment]
rewriting logical operations tests

**Comment by Abigael-JT** [comment]
new test data created for logical operation tests, rewriting unit tests in progress

**Comment by 51-code** [comment]
EarliestLatestTest has some disabled tests that need to be converted to use streaming datasets. The disabled tests are testing the default configuration on earliest and latest. There is a dataCustomizations consumer that can be used in this case.
