### ISSUE TITLE
Bind spark listening and server to localhost in tests

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/pth_10#296]
**Description**

Bind spark listening and server to localhost in tests.

**Use case or motivation behind the feature request**

Frewall rules can cause tests to timeout in certain environments if it decides to access the spark server via public ip and firewall drops such traffic

**Related issues**

 
**Additional context**

https://spark.apache.org/docs/latest/configuration.html#networking

**Comment by StrongestNumber9** [comment]
Maybe lowering `spark.network.timeout` to something like 5 seconds is useful as something has gone catastrophically wrong if we stall for even 5 seconds with networking when testing locally

**Comment by eemhu** [comment]
internal PR submitted
