### ISSUE TITLE
Move syntaxError tests to PTH-03

### ISSUE THREAD

**Issue by Abigael-JT** [teragrep/pth_10#322]
**Description**

These syntax error tests are currently disabled in PTH-10, and  should be moved to PTH-03 tests.

This will be worked on in issue https://github.com/teragrep/pth_10/issues/295

**Comment by 51-code** [comment]
Should look into how to assert an exact exception message in pth-03 unit tests, the InvocationTargetException that gets thrown in the tests for a syntax error doesn't include any message at least.

**Comment by Abigael-JT** [comment]
PR: https://github.com/teragrep/pth_10/pull/346
