### ISSUE TITLE
sort command broken

### ISSUE THREAD

**Issue by 51-code** [teragrep/pth_10#36]
ID <481>
Reporter <@kortemik>

it was reported that

`| teragrep exec hdfs load abc | rex field=_raw "bar=(?<foo>\d+) | stats count by foo | where count > 3 | where len(foo) > 0 | table foo, count | sort -count`

does not work correctly

**Comment by 51-code** [comment]
UI was sorting the results, overriding the sort command. The sorting is as expected now that the UI has the ordering setting off.

However, a problem with the same query remains where there is duplicated data rows. BatchCollect saves the dataset of each batch to sort them all together, but StepList uses each batch's sorted dataset to execute the following steps. This leads to a cumulative effect of duplicating data. Only the last returning dataset should be used after the sort command.

Only noticable with large datasets to be sorted, as smaller ones come in a single batch to the sort command. Recreating this behavior requires an aggregate command before the sort, as this will put StepList into forEachBatch / sequential mode.

**Comment by kortemik** [comment]
I think aggregated data should be sortable with

 https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/Dataset.html#orderBy-java.lang.String-java.lang.String...- 

because it is no longer streaming. Using BatchCollect after any aggregation is just plain wrong.

**Comment by 51-code** [comment]
Creating a way for Steps to know whether an aggregate is used before. Related to issue #152
