### ISSUE TITLE
teragrep exec bloomfilter create produces no filter for partitions without tokens

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#402]
**Describe the bug**
teragrep exec bloomfilter create produces no filter for partitions without tokens
 
**Expected behavior**
empty filter must be produced
 
**How to reproduce**
use non-matching regex for a partition
 
**Screenshots**

 
**Software version**
7.2.5
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by elliVM** [comment]
Currently testing in QA if fixed after #404

**Comment by elliVM** [comment]
After testing when estimate is 0 the smalles filter is selected and written to database. Archive queries correctly filter out the files if a pattern match query is performed.
