### ISSUE TITLE
add support for specifying bloomfilter table name within dpl

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#410]
**Description**
add support for specifying bloomfilter table name within dpl.

currently uses dpl.pth_06.bloom.table.name, this should be within the command itself:

```
... | teragrep exec bloom create table myTable [regex \w{4}]...
```

**Comment by 51-code** [comment]
dpl.pth_06.bloom.pattern will be moved to the command itself as well, as shown in the query example.
