### ISSUE TITLE
fix issues pointed in pr #414

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#440]
**Description**

- in [src/main/java/com/teragrep/pth10/steps/teragrep/bloomfilter/ToBloomFilter.java](https://github.com/teragrep/pth_10/pull/414/files/9f8786bce0361be8072e010b511973083a3516d7#diff-905063f43c4a54ba658a17865adeccef2c412be144e4ccf8063bc6a81d38eb56) asymmetry between equals and hashCode, this must be fixed
- add equalsveririfer for the new objects created
- consider renaming ModeFromBloomContext -> ContextBloomMode

**Comment by 51-code** [comment]
Equalsverifier doesn't work in classes with an ANTLR context as a field. Probably related to the generation of these contexts (part of a generated parse tree) which equalsverifier can't replicate.

**Comment by 51-code** [comment]
Steps have to be refactored. Right now, every step extends AbstractStep which has mutable fields and therefore equalsverifier tests will fail.
