### ISSUE TITLE
First does not seem to be working

### ISSUE THREAD

**Issue by kortemik** [teragrep/pth_10#64]
ID <452>
Reporter <@JohnJacobGuy>

Command stats would benefit from having option first.
Might be related to issue #160.

You can test this with following script with test index product.

%dpl 
index=products
| rex4j field=_raw "products=(?<product>[\w]+)"
| sort + product
| stats first(product)

#161

**Comment by 51-code** [comment]
I looked a the internal issue of this as well. There was a screenshot showing that the `| stats first(product)` didn't affect the query at all.

The products index isn't in use anymore, so I constructed the following query to test this with:
```
%dpl
index=abc
| rex4j field=_raw "\"timestamp_epoch\": (?<epoch>\d+)"
| sort + epoch
| stats first(epoch)
```
The query produces correct results, which is the earliest epoch timestamp.
